; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = credentials.ini

[env:esp32dev]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    knolleary/PubSubClient   ; MQTT
monitor_speed = 115200


build_flags =
    '-DWIFI_SSID="${credentials.WIFI_SSID}"'
    '-DWIFI_PASSWORD="${credentials.WIFI_PASSWORD}"'
    '-DMQTT_HOST="${credentials.MQTT_HOST}"'
    '-DMQTT_USER="${credentials.MQTT_USER}"'
    '-DMQTT_PASSWORD="${credentials.MQTT_PASSWORD}"'